<h1>Privacy</h1>
<p><?php echo getConfig()->get('site')->name; ?> is committed to protecting the privacy of its users, and making your <?php echo getConfig()->get('site')->name; ?> experience enjoyable and safe. Our data collection policies with regard to current and future services allow you to choose how much information you provide to us, and to control how we use that information. Read below to find out more.</p>
<h3>Privacy Philosophy</h3>
<p>The Internet is rapidly changing the way we communicate and interact with each other. While the Internet allows us access to a greater array of information and services than has ever been available, these new online activities do raise new challenges, such as the privacy issues addressed in this policy. Having a relationship with our customers that is founded on trust is not only good manners, it is also good business. Any feedback you'd like to provide to help us better meet your expectations in this arena is welcomed. <?php echo getConfig()->get('site')->name; ?> wants to make your online experience satisfying and safe. Our goal is to provide you with a robust online experience while allowing you to control your privacy. <?php echo getConfig()->get('site')->name; ?> collects information online primarily to make it easier and more rewarding for you to use our services. We request information from you in order to provide our strongest value to you - a personalized online experience. Customers who personalize our service come back more often - and it's the customers that visit us often who make us successful - so we do everything we can to make <?php echo getConfig()->get('site')->name; ?> your service with your name on it and to give you just the content you want.</p>
<h3>Information We Collect</h3>
<p>
  Information collected online is often defined as being either anonymous or personally identifiable:
  <p>
    <strong>Anonymous Information</strong> refers to information that cannot be tied back to a specific individual. For instance, we may know that 10,000 people visit this Privacy Policy today, but we do not necessarily know their names, where they live, or their date of birth. What we collect from transactions such as this constitutes anonymous information, much like how your hometown's bus service knows how many people take a given route - but doesn't necessarily know who those people are. Many of the individuals who access our services decline to use the personalization features that are available to them, and therefore those individuals are anonymous to us and the data we collect is similarly anonymous information.
  </p>
  <p>
    <strong>Personally Identifiable Information</strong> refers to information that is unique to you, such as your name or email address. In many cases we need this information to provide the personalized or enhanced service that you have requested. An example of the use of such information would be the <?php echo getConfig()->get('site')->name; ?> Groups. We hope that, like many of our customers, you will find it beneficial to judiciously provide Personally Identifiable Information to <?php echo getConfig()->get('site')->name; ?> so that we may provide more valuable content and products to you. The only way we know something about you personally is if you register as a user on our site. In other words, we will know Personally Identifiable Information about you only if you choose to share this type of information with us. Depending on the service you are accessing, you could be asked at various times to provide information such as your name, email address, or information about what you like and do not like. On other occasions such as when we provide items for purchase online, we may request your credit card number to conclude the transaction, or your mailing address to ensure proper delivery.
  </p>
</p>
<h3>Our Commitment to Your Family</h3>
<p>We have established a special policy with regard to the use of our services by children. The Federal Children's Online Privacy Protection Act of 1998 (COPPA) requires that service providers never knowingly request Personally Identifiable Information from anyone under the age of 13 without requesting verifiable parental consent. In accordance with COPPA, <?php echo getConfig()->get('site')->name; ?> does not knowingly collect any Personally Identifiable Information from children under the age of 13. No one under the age of 15 should submit any Personally Identifiable Information to our Site. In the event that <?php echo getConfig()->get('site')->name; ?> determines that a user of this site is under the age of 13, <?php echo getConfig()->get('site')->name; ?> will not maintain or use his or her Personally Identifiable Information. To ensure children's privacy, we urge parents and guardians to spend time online with their children to become familiar with the types of content available on the Internet. Control tools are available on the Internet from online services and software manufacturers to help create a safer environment for children. For additional information on protecting children's privacy, visit <a href="http://www.ftc.gov/bcp/conline/edcams/kidzprivacy/index.html">http://www.ftc.gov/bcp/conline/edcams/kidzprivacy/index.html</a>.</p>
<h3>Our Use of Personally Identifiable Information</h3>
<p>We are committed to making <?php echo getConfig()->get('site')->name; ?> enjoyable and safe. When you download our software, register for our online services, the information you provide to us is used to customize your experience and to deliver email notifications to you (or people you designate as your recipients). The names and email addresses you give us are NOT sold, compiled into any type of mailing list, or otherwise used for any type of email solicitation. We may use the information we collect to complete the purchase and delivery of products or services you order from us, to continuously improve this site and our business, and to customize and improve your online experience. We may at times send you information regarding important changes to your account or our service. We may also send you news, updates and other information you may find useful.</p>
<h3>Except as described below, we do not share your Personally Identifiable Information with third parties</h3>
<p>
  <ul>
    <li>We may share your information with our business partners and agents (such as Federal Express) only to the extent necessary to complete the purchase and delivery of your order. </li>
    <li>In the event that all or part of our business is sold or pledged as security, we may transfer the information we collect on this site to third parties in connection with that transaction. </li>
    <li>We may release personal information when we believe release is appropriate for any of the following purposes: to comply with the law or a request by law enforcement officials or judicial authorities; to enforce or apply our <a href="/terms">Terms of Use</a> and other agreements; or to protect the rights, property, or safety of <?php echo getConfig()->get('site')->name; ?>, our customers or others. This does NOT include selling, renting, sharing, or otherwise disclosing Personally Identifiable Information for commercial purposes. </li>
  </ul>
</p>
<h3>Cookies</h3>
<p>To enable many of the features provided by <?php echo getConfig()->get('site')->name; ?>, we will assign "cookies" to your Internet browser (such as Netscape Navigator or Microsoft Internet Explorer). A cookie is a small text file that contains a unique identification number stored on your computer. Cookies by themselves cannot be used to find out the identity of any user. This unique identification number automatically identifies your browser - but not you - to our computers whenever you interact on our site. When you visit our site, a cookie in effect says to our server computers, "Hello, I'm browser #733. What do you do just for me?" Every Web page that you access that includes advertising or content served from <?php echo getConfig()->get('site')->name; ?> will have the contents of your cookie reported in our server logs. Cookies are an essential part of how the Internet works today, and allow server computers to recognize your computer's browser when you return. If you have ever gone to a Web page that automatically provides personalized content without you having to "sign in," this is almost certainly being accomplished with a cookie. Since cookies are only text files, they cannot "run" on your computer and have no ability to search for or transmit other information from your computer.</p>
<h3>Security of Information</h3>
<p><?php echo getConfig()->get('site')->name; ?> operates secure data networks protected by industry standard firewall and password protection systems. Our security and privacy policies are periodically reviewed and enhanced as necessary, and only authorized individuals have access to the information provided by our customers. Any particularly sensitive information, such as a customer's credit card number collected for a commerce transaction, is encrypted prior to transmission. You the consumer are ultimately responsible for the security of your <?php echo getConfig()->get('site')->name; ?> username and password. Please take care to store your <?php echo getConfig()->get('site')->name; ?> Username separately from your account password, or better yet, choose a password that you don't need to write down at all.</p>
<h3>How You Can Correct any Inaccuracies</h3>
<p><?php echo getConfig()->get('site')->name; ?> believes strongly in providing you with the ability to access and edit the personal information that you have provided to us.</p>
<h3>General</h3>
<p>If you choose to visit our Web site, your visit and any dispute over privacy is subject to this Privacy Policy and our <a href="/terms">Terms of Use</a> including limitations on liability, arbitration of disputes, and application of the law of the United States and the state of Ohio . This Privacy Policy is subject to change at any time. Any changes will be set forth on this page.</p>
